### ISSUE TITLE
Turn off caching?

### ISSUE THREAD

**Issue by orophix** [denysvitali/raria2#1]
Is there a way to turn off caching?

**Comment by denysvitali** [comment]
Hey @orophix,

sure thing it should be possible: is there any particular aria2c argument you want to use?

Look at this part:
https://github.com/denysvitali/raria2/blob/master/pkg/lib.go#L213

**Comment by orophix** [comment]
Well separately to that question, I'd like to use` --conf-path=<PATH>` as well, 
Would I just change to:
`args := []string{"-x", strconv.Itoa(r.ParallelConnectionsPerJob), "-d", outputDir, "--conf-path=<PATH>"}`

When using raria for some reason its filling up my hd with cache. Does raria ignore the aria2c configuration or is logrus the cause?

**Comment by denysvitali** [comment]
> Would I just change to:
> `args := []string{"-x", strconv.Itoa(r.ParallelConnectionsPerJob), "-d", outputDir, --conf-path=<PATH>}`

Yep :)



> When using raria for some reason its filling up my hd with cache. Does raria ignore the aria2c configuration or is logrus the cause?

raria is just a wrapper of the aria2c command, with the options mentioned before, logrus is our logging interface and has nothing to do with the communication aria2c <-> raria

**Comment by orophix** [comment]
Thanks a lot!
